### ISSUE TITLE
Export Image doesn't export background

### ISSUE THREAD

**Issue by prograk** [vinothpandian/react-sketch-canvas#13]
**Describe the bug**
When use exportImage it exports to base64 without the background image that was added to canvas.

**To Reproduce**
1. add background image in canvas.
2. Draw on canvas with a bgimage
3. exportImage jpeg 
4. img tag will only have strokes without background of canvas

**Expected behavior**
it should contain background image with strokes on it in base64 url.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu
 - Browser: Chrome

**Comment by vinothpandian** [comment]
Hey @prograk,

This behaviour is as per design. I had a use-case where I show the background frame but that should be excluded in the final export.

It is possible to add the background, so if you could add it please make a pull request. Otherwise, I will set it for future enhancement and update it later.

**Comment by nvminhhieu** [comment]
Hi! I am also interested in this feature. Are there any news of it?

**Comment by vinothpandian** [comment]
Not yet. I can take a look at it next month. In the meantime, if you find a solution, please make a pull request.
